// Content sourced from ISMS_U02 - Acceptable Usage Policy v5.7 (Aitken Spence PLC)

export const meta = {
  docId: 'ISMS-U02',
  title: 'Acceptable Usage Policy',
  version: 'v5.7',
  owner: 'ISMS Steering Committee',
  org: 'Aitken Spence PLC',
}

export const sections = [
  {
    id: 'overview',
    num: '1',
    title: 'Overview',
    blocks: [
      { type: 'para', text: 'The intention for publishing this Acceptable Usage Policy is to protect employees, partners, and the company from damage or illegal activity, whether knowingly or unknowingly. It is not intended to impose restrictions that are contrary to Aitken Spence\u2019s established culture of openness, trust, and integrity.' },
      { type: 'para', text: 'Effective security is a team effort involving the participation and support of every Aitken Spence employee and affiliate who deals with information and/or information systems. It is the responsibility of every employee/user to know these guidelines and to conduct their activities accordingly.' },
    ],
  },
  {
    id: 'purpose',
    num: '2',
    title: 'Purpose',
    blocks: [
      { type: 'para', text: 'The purpose of this policy is to outline the acceptable use of information, digital infrastructure, and intellectual & digital proprietary property at Aitken Spence. These rules are in place to protect both employees and the company. Inappropriate use exposes the company to risks including legal, reputational, and cyber threats. This document establishes guidelines and the chart of authority for decisions on the said space.' },
      { type: 'subhead', num: '2.1', text: 'Information Security' },
      { type: 'para', text: 'Information Security is the responsibility of all staff, contractors, and third-party vendors associated with Aitken Spence\u2019s Information Technology & Systems. Information Security can be defined as \u201cthe state of being free from unacceptable risk.\u201d The risk relates to, but is not limited to, the following areas:' },
      { type: 'list', items: [
        { num: '2.1.1', title: 'Confidentiality of Information', text: 'Refers to the privacy of personal or business information associated with Aitken Spence and its SBUs.' },
        { num: '2.1.2', title: 'Integrity of Data', text: 'Refers to the accuracy of data. Data integrity is critical for informed decision-making, collation of information, and formulation of reports. Therefore, the risk of data loss or alteration, whether accidental or malicious, must be managed.' },
        { num: '2.1.3', title: 'Availability of Systems', text: 'Refers to ensuring full functionality of IT systems and their components at all times, as per applicable Service Level Agreements.' },
        { num: '2.1.4', title: 'Information Technology & Systems Assets', text: 'Refers to assets including, but not limited to, physical assets, applications, cloud instances, license properties, system code, and data.' },
        { num: '2.1.5', title: 'Efficient and Appropriate Use of IT Systems', text: 'Refers to the correct and secure use of IT systems, applications, data, and digital media containing organizational information.' },
      ]},
      { type: 'subhead', num: '2.2', text: 'Threats' },
      { type: 'para', text: 'The term \u201cthreats\u201d refers to potential causes of losses to confidentiality, integrity, or availability of Information Technology & Systems. Threats may be internal, external, human, non-human, natural, accidental, or deliberate.' },
      { type: 'para', text: 'Failure to maintain confidentiality, integrity, or availability of Information Technology & Systems may negatively impact the company. This policy aims to establish mechanisms to manage these threats and reduce the company\u2019s exposure.' },
      { type: 'subhead', num: '2.3', text: 'Reporting Security Incidents' },
      { type: 'para', text: 'All employees have a responsibility to report any incidents that may have security significance to the company. Reporting and escalation should be done as per the Information Security Manager\u2019s published channel.' },
    ],
  },
  {
    id: 'scope',
    num: '3',
    title: 'Scope of Applicability',
    blocks: [
      { type: 'para', text: 'This policy applies to all employees and third-party/contract staff in their use of digital, electronic, and manual information; communication and computing devices; and social and mass media when conducting Aitken Spence business.' },
    ],
  },
  {
    id: 'policy',
    num: '4',
    title: 'Policy',
    blocks: [
      { type: 'subhead', num: '4.1', text: 'General Use and Ownership' },
      { type: 'orderedList', items: [
        { num: '4.1.1', text: 'Aitken Spence proprietary information, stored in any form (electronic, digital, computing devices, or hard copy), whether owned or leased by Aitken Spence, the employee, or a third party, remains the sole property of Aitken Spence.' },
        { num: '4.1.2', text: 'All assets, including employee working time, must be used only for business-related matters and not for personal or unofficial interests.' },
        { num: '4.1.3', text: 'All employees, contractors, or third parties are responsible for reporting any violation within 8 hours of interception, as per Section 2.3 of this policy.' },
        { num: '4.1.4', text: 'Employees may access, use, or share Aitken Spence proprietary information only to the extent authorized and necessary to fulfill assigned job duties.' },
        { num: '4.1.5', text: 'It is the responsibility of the information custodian to classify information based on its criticality or confidentiality.' },
        { num: '4.1.6', text: 'Any SBU of Aitken Spence may develop their own policies, provided such policies are not less restrictive than this policy.' },
        { num: '4.1.7', text: 'For governance and network maintenance purposes, authorized individuals in Aitken Spence\u2019s Group IT, or parties permitted to do so, may monitor equipment, systems, or network traffic in accordance with Aitken Spence\u2019s Audit Logging and Monitoring Policy. This does not overrule confidentiality and privacy obligations. Information classified as \u201cHighly Confidential\u201d shall not be accessed, intentionally or unintentionally, unless explicitly authorized.' },
        { num: '4.1.8', text: 'Aitken Spence Group IT reserves the right to audit networks and systems periodically to ensure compliance with this policy.' },
      ]},
      { type: 'subhead', num: '4.2', text: 'Security and Proprietary Information' },
      { type: 'para', text: 'All mobile computing devices connecting to the internal network must comply with the Minimum Access Criteria, which include:' },
      { type: 'list', items: [
        { text: 'Use of a strong password (not patterns).' },
        { text: 'Screen lockout time of 5 minutes or less.' },
        { text: 'Devices not \u201crooted\u201d or \u201cjailbroken.\u201d' },
        { text: 'Multi-Factor Authentication (MFA) enabled.' },
      ]},
      { type: 'orderedList', items: [
        { num: '4.2.2', text: 'System-level and user-level passwords must comply with the Password Policy. Sharing access with another individual, either deliberately or through negligence, is prohibited.' },
        { num: '4.2.3', text: 'All computing devices must be secured with a password-protected screensaver and automatic lockout set to 5 minutes or less. Devices must be locked or logged off when unattended.' },
        { num: '4.2.4', text: 'Posts from a company email address to newsgroups must include a disclaimer that opinions expressed are personal and not necessarily those of Aitken Spence, unless posting is part of official duties.' },
        { num: '4.2.5', text: 'Employees must exercise extreme caution when opening email attachments from unknown senders, as they may contain malware.' },
      ]},
      { type: 'subhead', num: '4.3', text: 'Unacceptable and Prohibited Use' },
      { type: 'para', text: 'Under no circumstances may employees engage in activities that are illegal under local or international law while using Aitken Spence resources. The following lists, though not exhaustive, provide a framework of prohibited activities.' },
      { type: 'restricted-head', num: '4.3.1', text: 'System and Network Activities' },
      { type: 'restricted', items: [
        'Violating intellectual property rights, including installing or distributing unlicensed or pirated software.',
        'Unauthorized copying of copyrighted materials (e.g., books, music, software).',
        'Accessing data, servers, or accounts for non-business or illegitimate purposes.',
        'Importing/exporting software or technical information in violation of export control laws.',
        'Introducing malicious programs (viruses, worms, trojans, ransomware, etc.).',
        'Sharing account credentials or allowing account use by others.',
        'Viewing, downloading, or storing pornographic or racist material.',
        'Making fraudulent offers of products, items, or services.',
        'Security breaches or disruptions (e.g., denial of service, sniffing, spoofing).',
        'Port or security scanning without prior approval.',
        'Unauthorized network monitoring or interception of data.',
        'Circumventing authentication or security controls.',
        'Introducing honeypots/honeynets.',
        'Denial-of-service attacks.',
        'Using scripts/commands to interfere with user sessions.',
        'Providing internal information to external parties.',
        'Connecting to external/personal Wi-Fi while on company network.',
        'Connecting unauthorized third-party devices to company network.',
      ]},
      { type: 'restricted-head', num: '4.3.2', text: 'Electronic Communication Activities' },
      { type: 'para', text: 'Employees must recognize that when using company resources to access the internet, they represent the company. Clarifications may be sought from Group IT. Prohibited activities include:' },
      { type: 'restricted', items: [
        'Sending unsolicited emails (spam).',
        'Harassment through email, calls, or messages.',
        'Sending oversized group messages that disrupt system capacity.',
        'Forging or misusing email header information.',
        'Soliciting identification or replies for harassment.',
        'Forwarding chain letters, Ponzi, or pyramid schemes.',
        'Using unsolicited email for advertising via Aitken Spence networks.',
        'Posting repetitive non-business content (newsgroup spam).',
        'Using company communication for non-business matters.',
      ]},
      { type: 'restricted-head', num: '4.3.3', text: 'Blogging and Social Media' },
      { type: 'orderedList', items: [
        { num: '4.3.3.1', text: 'Communication (via company or personal systems) must remain professional, responsible, and compliant with this policy.' },
        { num: '4.3.3.2', text: 'Employees must not reveal confidential/proprietary information.' },
        { num: '4.3.3.3', text: 'Prohibited content includes discriminatory, defamatory, disparaging, or harassing comments.' },
        { num: '4.3.3.4', text: 'Employees must not attribute personal opinions to Aitken Spence.' },
        { num: '4.3.3.5', text: 'Unauthorized use of Aitken Spence trademarks, logos, or software in blogs/posts is prohibited.' },
        { num: '4.3.3.6', text: 'Communication applications must securely identify the user, integrate with Active Directory or equivalent authentication, support secure messaging, be limited to company-provided numbers/devices for apps like WhatsApp, Viber or Skype (with approval), and must not include unauthorized accounts associated with the company.' },
      ]},
      { type: 'note', text: 'Refer to ISMS U39 \u2013 Instant Messaging and Private Communication Apps Policy for full details.' },
      { type: 'restricted-head', num: '4.3.4', text: 'Remote Work Access' },
      { type: 'para', text: 'Employees must strictly follow the company\u2019s remote work procedure under ISMS U28 \u2013 Access Control Policy (section on Mobile Computing and Teleworking) by obtaining proper authorization, using only approved devices, connecting securely through Group VPN with MFA, avoiding unauthorized tools or personal hotspots, notifying IT for overseas access, and not storing sensitive data locally. Public Wi-Fi may only be used when secured by VPN.' },
      { type: 'restricted-head', num: '4.3.5', text: 'Internet Use and Web Filtering' },
      { type: 'para', text: 'Employees are required to comply with the company\u2019s ISMS U37 \u2013 Internet Usage and Web Filtering Policy when accessing and using the internet.' },
      { type: 'restricted-head', num: '4.3.6', text: 'Artificial Intelligence (AI)' },
      { type: 'para', text: 'Employees must use Artificial Intelligence (AI) tools responsibly and in compliance with the company\u2019s ISMS U38 \u2013 Artificial Intelligence User Policy.' },
    ],
  },
  {
    id: 'compliances',
    num: '5',
    title: 'Compulsory Compliances and Behaviors',
    blocks: [
      { type: 'orderedList', items: [
        { num: '5.1', title: 'Storing of Company Data', text: 'All data must be stored in company-provided cloud storage. Local/removable storage use is prohibited, unless mirrored to corporate storage with IT approval.' },
        { num: '5.2', title: 'Transmission of Confidential Information', text: 'Confidential emails and attachments must be secured using rights management.' },
        { num: '5.3', title: 'Configuration of Company Devices and Accounts', text: 'Devices/accounts must be configured with the company email as recovery.' },
        { num: '5.4', title: 'Email Naming Conventions', text: 'Employee emails must follow employee_preferred_name@aitkenspence.lk. Shared emails must follow usage.businessunit.sector@aitkenspence.lk.' },
        { num: '5.5', title: 'Eligibility for Company Email', text: 'Only employees/contract staff with a valid employee number may have company emails. Non-executive directors are typically excluded, unless approved by the Deputy Chairman.' },
        { num: '5.6', title: 'Change Management and Issue Resolution', text: 'All IT changes and support requests must be logged via the Freshservice Helpdesk. Off-system requests will not be supported.' },
      ]},
    ],
  },
  {
    id: 'classification',
    num: '6',
    title: 'Information Classification',
    blocks: [
      { type: 'para', text: 'Employees are required to strictly adhere to the Company\u2019s Information Classification Policy. All information must be handled, stored, transmitted, and disposed of according to its designated classification level to ensure confidentiality, integrity, and availability.' },
      { type: 'classTable', rows: [
        { level: 'Highly Confidential', desc: 'Access restricted to explicitly named individuals; unauthorized access is a policy breach even if accidental.' },
        { level: 'Confidential', desc: 'Restricted to those with a legitimate business need to know.' },
        { level: 'Internal', desc: 'For use within Aitken Spence and its SBUs; not for external distribution.' },
        { level: 'Public', desc: 'Approved for release outside the company.' },
      ]},
      { type: 'para', text: 'Classified Confidential Information includes, but is not limited to:' },
      { type: 'list', items: [
        { text: 'Payroll, salary, and remuneration information.' },
        { text: 'Board papers and management discussions/decisions.' },
        { text: 'Organizational security-related information.' },
        { text: 'Employee personal information.' },
        { text: 'Any information classified as \u201cHighly Confidential.\u201d' },
      ]},
    ],
  },
  {
    id: 'social',
    num: '7',
    title: 'Use of Social Media and Domain Names',
    blocks: [
      { type: 'orderedList', items: [
        { num: '7.1', text: 'Social media accounts are the responsibility of each sector head, who must maintain an inventory.' },
        { num: '7.2', text: 'Accounts must be created with recovery email: recovery@aitkenspence.lk.' },
        { num: '7.3', text: 'Domain names, tenants, website, and social media credentials must be held only by Group IT.' },
      ]},
    ],
  },
  {
    id: 'compliance',
    num: '8',
    title: 'Policy Compliance',
    blocks: [
      { type: 'orderedList', items: [
        { num: '8.1', title: 'Compliance Measurement', text: 'Group IT will verify compliance via reports, audits, and feedback. Violations will be escalated to the Group Supervisory Board and/or ISMS Steering Committee.' },
        { num: '8.2', title: 'Compliance with Legal and Regulatory Requirements', text: 'All employees, contractors, and third parties must comply with applicable laws and regulations on data privacy, information security, and IPR.' },
        { num: '8.3', title: 'Exceptions', text: 'Must be pre-approved by the ISMS team, with written undertaking by the respective SBU Managing Director.' },
        { num: '8.4', title: 'Non-Compliance', text: 'Violations may result in disciplinary action, up to termination.' },
        { num: '8.5', title: 'Breach of Policy', text: 'Any external influence or error causing a breach must be reported in writing and handled via escalation as per Section 2.3.' },
      ]},
    ],
  },
  {
    id: 'related',
    num: '9',
    title: 'Related Standards, Policies, and Processes',
    blocks: [
      { type: 'list', items: [
        { text: 'Access Control Policy' },
        { text: 'Information Classification Policy' },
        { text: 'Password Policy' },
        { text: 'Disciplinary Policy' },
        { text: 'Clear Desk and Clear Screen Policy' },
        { text: 'Artificial Intelligence (AI) Policy' },
      ]},
    ],
  },
]

export const consentSectionId = 'consent'
